// Generated by GithubCopilot
/**
 * Express server entry point for the Media Provenance Registry API.
 *
 * Security:
 * - Helmet for HTTP security headers (CSP, HSTS, etc.)
 * - CORS configured for controlled access
 * - Rate limiting via request size limits
 * - Input validation on all endpoints
 *
 * Green Software: Single-process SQLite backend, no idle resource waste.
 */

import express from "express";
import cors from "cors";
import helmet from "helmet";
import { MediaRegistry } from "../storage/registry";
import { createApiRouter } from "./routes";

const PORT = parseInt(process.env.PORT ?? "3210", 10);
const DB_PATH = process.env.DB_PATH ?? undefined;

const app = express();

// Security headers
app.use(helmet());

// CORS — allow all origins for public verification access
app.use(
  cors({
    origin: "*",
    methods: ["GET", "POST"],
    allowedHeaders: ["Content-Type", "Authorization"],
  }),
);

// Parse JSON bodies (limit to 1 MB for non-file requests)
app.use(express.json({ limit: "1mb" }));
app.use(express.urlencoded({ extended: true, limit: "1mb" }));

// Initialize registry
const registry = new MediaRegistry(DB_PATH);

// Mount API routes
app.use("/api/v1", createApiRouter(registry));

// Health check
app.get("/health", (_req, res) => {
  res.json({
    status: "healthy",
    service: "Media Provenance Registry",
    version: "1.0.0",
    registeredMedia: registry.getCount(),
    timestamp: new Date().toISOString(),
  });
});

// Root info endpoint
app.get("/", (_req, res) => {
  res.json({
    name: "Media Provenance & Integrity Verification System",
    version: "1.0.0",
    description:
      "Assigns cryptographic identity to every image and video capture, " +
      "enabling anyone to verify authenticity and integrity.",
    endpoints: {
      register: "POST   /api/v1/register",
      registerUpload: "POST   /api/v1/register/upload",
      verifyUpload: "POST   /api/v1/verify/upload",
      verifyHash: "GET    /api/v1/verify/:hash",
      lookupById: "GET    /api/v1/lookup/id/:mediaId",
      lookupByCode: "GET    /api/v1/lookup/code/:identityCode",
      lookupByDevice: "GET    /api/v1/lookup/device/:publicKey",
      stats: "GET    /api/v1/stats",
      health: "GET    /health",
    },
  });
});

// Graceful shutdown
process.on("SIGINT", () => {
  console.log("\nShutting down gracefully...");
  registry.close();
  process.exit(0);
});

process.on("SIGTERM", () => {
  registry.close();
  process.exit(0);
});

// Start server
app.listen(PORT, () => {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║       Media Provenance & Integrity Verification System      ║
╠══════════════════════════════════════════════════════════════╣
║  Server running on: http://localhost:${PORT}                   ║
║  Registry entries:  ${String(registry.getCount()).padEnd(39)}║
║                                                              ║
║  API Docs:          http://localhost:${PORT}/                   ║
║  Health Check:      http://localhost:${PORT}/health              ║
╚══════════════════════════════════════════════════════════════╝
  `);
});

export default app;
