// Generated by GithubCopilot
/**
 * API Route Handlers — Express routes for the Media Provenance Registry.
 *
 * Endpoints:
 *   POST   /api/v1/register           — Register a new media identity
 *   POST   /api/v1/register/upload     — Register with media file upload
 *   POST   /api/v1/verify/upload       — Verify a media file by uploading it
 *   GET    /api/v1/verify/:hash        — Look up identity by content hash
 *   GET    /api/v1/lookup/id/:mediaId  — Look up by media ID
 *   GET    /api/v1/lookup/code/:code   — Look up by identity code
 *   GET    /api/v1/lookup/device/:key  — List identities by device public key
 *   GET    /api/v1/stats               — Registry statistics
 *
 * Security: All inputs are validated. Helmet adds security headers.
 * Accessibility: JSON responses include human-readable summaries.
 */

import { Router, Request, Response } from "express";
import multer from "multer";
import { MediaRegistry } from "../storage/registry";
import {
  hashContent,
  computeFingerprint,
  verifySignature,
  generateMediaId,
  generateIdentityCode,
} from "../core/crypto";
import { verifyMedia } from "../core/verification";
import {
  RegisterRequestSchema,
  HashSchema,
  UuidSchema,
  IdentityCodeSchema,
} from "./validation";
import type {
  ApiResponse,
  MediaIdentity,
  RegistryRecord,
  VerificationResult,
} from "../types";

// Configure multer for file uploads (50 MB limit)
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 50 * 1024 * 1024 },
  fileFilter: (_req, file, cb) => {
    if (
      file.mimetype.startsWith("image/") ||
      file.mimetype.startsWith("video/")
    ) {
      cb(null, true);
    } else {
      cb(new Error("Only image and video files are allowed"));
    }
  },
});

/**
 * Create the API router with all endpoints.
 *
 * @param registry - The media registry instance
 * @returns Express Router
 */
export function createApiRouter(registry: MediaRegistry): Router {
  const router = Router();

  /**
   * POST /api/v1/register
   * Register a pre-computed media identity (from mobile device).
   * The device computes hashes and signs locally, then sends the identity.
   */
  router.post("/register", (req: Request, res: Response) => {
    try {
      const parsed = RegisterRequestSchema.safeParse(req.body);
      if (!parsed.success) {
        const response: ApiResponse<null> = {
          success: false,
          error: `Validation failed: ${parsed.error.issues.map((i) => i.message).join(", ")}`,
          timestamp: new Date().toISOString(),
        };
        res.status(400).json(response);
        return;
      }

      const data = parsed.data;

      // Verify the fingerprint is correctly computed
      const expectedFingerprint = computeFingerprint(
        data.contentHash,
        data.metadataHash,
      );
      if (expectedFingerprint !== data.fingerprint) {
        const response: ApiResponse<null> = {
          success: false,
          error: "Fingerprint does not match content hash + metadata hash",
          timestamp: new Date().toISOString(),
        };
        res.status(400).json(response);
        return;
      }

      // Verify the digital signature
      const signatureValid = verifySignature(
        data.fingerprint,
        data.signature,
        data.publicKey,
      );
      if (!signatureValid) {
        const response: ApiResponse<null> = {
          success: false,
          error: "Digital signature verification failed",
          timestamp: new Date().toISOString(),
        };
        res.status(400).json(response);
        return;
      }

      // Check for duplicate
      const existing = registry.findByContentHash(data.contentHash);
      if (existing) {
        const response: ApiResponse<RegistryRecord> = {
          success: false,
          error: "This media has already been registered",
          data: existing,
          timestamp: new Date().toISOString(),
        };
        res.status(409).json(response);
        return;
      }

      // Create identity and register
      const identity: MediaIdentity = {
        mediaId: generateMediaId(),
        contentHash: data.contentHash,
        metadataHash: data.metadataHash,
        fingerprint: data.fingerprint,
        signature: data.signature,
        publicKey: data.publicKey,
        createdAt: new Date().toISOString(),
        metadata: data.metadata,
        identityCode: generateIdentityCode(data.fingerprint),
      };

      const record = registry.register(identity);

      const response: ApiResponse<RegistryRecord> = {
        success: true,
        data: record,
        timestamp: new Date().toISOString(),
      };
      res.status(201).json(response);
    } catch (err) {
      const response: ApiResponse<null> = {
        success: false,
        error: err instanceof Error ? err.message : "Internal server error",
        timestamp: new Date().toISOString(),
      };
      res.status(500).json(response);
    }
  });

  /**
   * POST /api/v1/register/upload
   * Register a media identity by uploading the actual file.
   * Server computes the content hash. Metadata and signature
   * are provided as JSON in the 'identity' form field.
   */
  router.post(
    "/register/upload",
    upload.single("media"),
    (req: Request, res: Response) => {
      try {
        if (!req.file) {
          const response: ApiResponse<null> = {
            success: false,
            error: "No media file uploaded",
            timestamp: new Date().toISOString(),
          };
          res.status(400).json(response);
          return;
        }

        const identityData = req.body.identity;
        if (!identityData) {
          const response: ApiResponse<null> = {
            success: false,
            error: "Missing identity data in form field",
            timestamp: new Date().toISOString(),
          };
          res.status(400).json(response);
          return;
        }

        let parsed;
        try {
          parsed = JSON.parse(identityData);
        } catch {
          const response: ApiResponse<null> = {
            success: false,
            error: "Invalid JSON in identity field",
            timestamp: new Date().toISOString(),
          };
          res.status(400).json(response);
          return;
        }

        // Compute content hash from uploaded file
        const contentHash = hashContent(req.file.buffer);

        // Verify the content hash matches what the device claimed
        if (parsed.contentHash && parsed.contentHash !== contentHash) {
          const response: ApiResponse<null> = {
            success: false,
            error:
              "Content hash mismatch — uploaded file does not match claimed hash",
            timestamp: new Date().toISOString(),
          };
          res.status(400).json(response);
          return;
        }

        // Set actual content hash
        parsed.contentHash = contentHash;

        // Validate the rest
        const validated = RegisterRequestSchema.safeParse(parsed);
        if (!validated.success) {
          const response: ApiResponse<null> = {
            success: false,
            error: `Validation failed: ${validated.error.issues.map((i) => i.message).join(", ")}`,
            timestamp: new Date().toISOString(),
          };
          res.status(400).json(response);
          return;
        }

        // Verify signature
        const signatureValid = verifySignature(
          validated.data.fingerprint,
          validated.data.signature,
          validated.data.publicKey,
        );
        if (!signatureValid) {
          const response: ApiResponse<null> = {
            success: false,
            error: "Digital signature verification failed",
            timestamp: new Date().toISOString(),
          };
          res.status(400).json(response);
          return;
        }

        // Check duplicate
        const existing = registry.findByContentHash(contentHash);
        if (existing) {
          const response: ApiResponse<RegistryRecord> = {
            success: false,
            error: "This media has already been registered",
            data: existing,
            timestamp: new Date().toISOString(),
          };
          res.status(409).json(response);
          return;
        }

        const identity: MediaIdentity = {
          mediaId: generateMediaId(),
          contentHash,
          metadataHash: validated.data.metadataHash,
          fingerprint: validated.data.fingerprint,
          signature: validated.data.signature,
          publicKey: validated.data.publicKey,
          createdAt: new Date().toISOString(),
          metadata: validated.data.metadata,
          identityCode: generateIdentityCode(validated.data.fingerprint),
        };

        const record = registry.register(identity);

        const response: ApiResponse<RegistryRecord> = {
          success: true,
          data: record,
          timestamp: new Date().toISOString(),
        };
        res.status(201).json(response);
      } catch (err) {
        const response: ApiResponse<null> = {
          success: false,
          error: err instanceof Error ? err.message : "Internal server error",
          timestamp: new Date().toISOString(),
        };
        res.status(500).json(response);
      }
    },
  );

  /**
   * POST /api/v1/verify/upload
   * Verify a media file by uploading it. The server computes
   * the content hash and looks it up in the registry.
   */
  router.post(
    "/verify/upload",
    upload.single("media"),
    (req: Request, res: Response) => {
      try {
        if (!req.file) {
          const response: ApiResponse<null> = {
            success: false,
            error: "No media file uploaded",
            timestamp: new Date().toISOString(),
          };
          res.status(400).json(response);
          return;
        }

        const contentHash = hashContent(req.file.buffer);
        const record = registry.findByContentHash(contentHash);

        if (!record) {
          const response: ApiResponse<VerificationResult> = {
            success: true,
            data: {
              isAuthentic: false,
              contentMatch: false,
              signatureValid: false,
              metadataIntact: false,
              summary:
                "❌ NOT FOUND — This media has no registered identity. " +
                "It may not have been captured through the provenance system, " +
                "or it may have been modified.",
              verifiedAt: new Date().toISOString(),
              warnings: ["No matching identity record found in the registry."],
            },
            timestamp: new Date().toISOString(),
          };
          res.status(200).json(response);
          return;
        }

        // Run full verification
        const result = verifyMedia(req.file.buffer, record);

        // Log the verification
        const verifierIp = req.ip ?? req.socket.remoteAddress;
        registry.logVerification(
          record.mediaId,
          result.isAuthentic,
          result.contentMatch,
          result.signatureValid,
          result.metadataIntact,
          verifierIp,
        );

        const response: ApiResponse<VerificationResult> = {
          success: true,
          data: result,
          timestamp: new Date().toISOString(),
        };
        res.status(200).json(response);
      } catch (err) {
        const response: ApiResponse<null> = {
          success: false,
          error: err instanceof Error ? err.message : "Internal server error",
          timestamp: new Date().toISOString(),
        };
        res.status(500).json(response);
      }
    },
  );

  /**
   * GET /api/v1/verify/:hash
   * Quick lookup and verification by content hash.
   * Useful when you have the hash but not the file.
   */
  router.get("/verify/:hash", (req: Request, res: Response) => {
    try {
      const hashResult = HashSchema.safeParse(req.params.hash);
      if (!hashResult.success) {
        const response: ApiResponse<null> = {
          success: false,
          error: "Invalid hash format. Must be a 64-char hex SHA-256 hash.",
          timestamp: new Date().toISOString(),
        };
        res.status(400).json(response);
        return;
      }

      const record = registry.findByContentHash(hashResult.data);
      if (!record) {
        const response: ApiResponse<null> = {
          success: false,
          error: "No media identity found for this content hash.",
          timestamp: new Date().toISOString(),
        };
        res.status(404).json(response);
        return;
      }

      // Verify signature
      const sigValid = verifySignature(
        record.fingerprint,
        record.signature,
        record.publicKey,
      );

      const response: ApiResponse<{
        record: RegistryRecord;
        signatureValid: boolean;
      }> = {
        success: true,
        data: { record, signatureValid: sigValid },
        timestamp: new Date().toISOString(),
      };
      res.status(200).json(response);
    } catch (err) {
      const response: ApiResponse<null> = {
        success: false,
        error: err instanceof Error ? err.message : "Internal server error",
        timestamp: new Date().toISOString(),
      };
      res.status(500).json(response);
    }
  });

  /**
   * GET /api/v1/lookup/id/:mediaId
   * Look up a media identity by its UUID.
   */
  router.get("/lookup/id/:mediaId", (req: Request, res: Response) => {
    try {
      const idResult = UuidSchema.safeParse(req.params.mediaId);
      if (!idResult.success) {
        const response: ApiResponse<null> = {
          success: false,
          error: "Invalid media ID format. Must be a valid UUID.",
          timestamp: new Date().toISOString(),
        };
        res.status(400).json(response);
        return;
      }

      const record = registry.findByMediaId(idResult.data);
      if (!record) {
        const response: ApiResponse<null> = {
          success: false,
          error: "No media identity found for this ID.",
          timestamp: new Date().toISOString(),
        };
        res.status(404).json(response);
        return;
      }

      const response: ApiResponse<RegistryRecord> = {
        success: true,
        data: record,
        timestamp: new Date().toISOString(),
      };
      res.status(200).json(response);
    } catch (err) {
      const response: ApiResponse<null> = {
        success: false,
        error: err instanceof Error ? err.message : "Internal server error",
        timestamp: new Date().toISOString(),
      };
      res.status(500).json(response);
    }
  });

  /**
   * GET /api/v1/lookup/code/:code
   * Look up by human-readable identity code (MPROV-XXXX-XXXX-XXXX).
   */
  router.get("/lookup/code/:code", (req: Request, res: Response) => {
    try {
      const codeResult = IdentityCodeSchema.safeParse(req.params.code);
      if (!codeResult.success) {
        const response: ApiResponse<null> = {
          success: false,
          error: "Invalid identity code format. Expected: MPROV-XXXX-XXXX-XXXX",
          timestamp: new Date().toISOString(),
        };
        res.status(400).json(response);
        return;
      }

      const record = registry.findByIdentityCode(codeResult.data);
      if (!record) {
        const response: ApiResponse<null> = {
          success: false,
          error: "No media identity found for this code.",
          timestamp: new Date().toISOString(),
        };
        res.status(404).json(response);
        return;
      }

      const response: ApiResponse<RegistryRecord> = {
        success: true,
        data: record,
        timestamp: new Date().toISOString(),
      };
      res.status(200).json(response);
    } catch (err) {
      const response: ApiResponse<null> = {
        success: false,
        error: err instanceof Error ? err.message : "Internal server error",
        timestamp: new Date().toISOString(),
      };
      res.status(500).json(response);
    }
  });

  /**
   * GET /api/v1/lookup/device/:publicKey
   * List all media registered by a specific device.
   */
  router.get("/lookup/device/:publicKey", (req: Request, res: Response) => {
    try {
      const publicKey = req.params.publicKey;
      if (!/^[a-f0-9]+$/.test(publicKey)) {
        const response: ApiResponse<null> = {
          success: false,
          error: "Invalid public key format. Must be hex-encoded.",
          timestamp: new Date().toISOString(),
        };
        res.status(400).json(response);
        return;
      }

      const limit = Math.min(Number(req.query.limit ?? 50), 200);
      const records = registry.findByDevice(publicKey, limit);

      const response: ApiResponse<{
        records: RegistryRecord[];
        count: number;
      }> = {
        success: true,
        data: { records, count: records.length },
        timestamp: new Date().toISOString(),
      };
      res.status(200).json(response);
    } catch (err) {
      const response: ApiResponse<null> = {
        success: false,
        error: err instanceof Error ? err.message : "Internal server error",
        timestamp: new Date().toISOString(),
      };
      res.status(500).json(response);
    }
  });

  /**
   * GET /api/v1/stats
   * Get registry statistics.
   */
  router.get("/stats", (_req: Request, res: Response) => {
    try {
      const totalRegistered = registry.getCount();
      const recent = registry.getRecent(5);

      const response: ApiResponse<{
        totalRegistered: number;
        recentRegistrations: RegistryRecord[];
      }> = {
        success: true,
        data: { totalRegistered, recentRegistrations: recent },
        timestamp: new Date().toISOString(),
      };
      res.status(200).json(response);
    } catch (err) {
      const response: ApiResponse<null> = {
        success: false,
        error: err instanceof Error ? err.message : "Internal server error",
        timestamp: new Date().toISOString(),
      };
      res.status(500).json(response);
    }
  });

  return router;
}
