// Generated by GithubCopilot
/**
 * Input validation schemas using Zod.
 *
 * Security: Strict validation prevents injection attacks and malformed data.
 * All API inputs are validated before processing.
 */

import { z } from "zod";
import { MediaType } from "../types";

/** Validate device info */
export const DeviceInfoSchema = z.object({
  manufacturer: z.string().min(1).max(100),
  model: z.string().min(1).max(100),
  osVersion: z.string().min(1).max(50),
  deviceIdHash: z
    .string()
    .regex(/^[a-f0-9]{64}$/, "Must be a SHA-256 hex hash"),
  cameraLens: z.string().max(50).optional(),
});

/** Validate geo location */
export const GeoLocationSchema = z.object({
  latitude: z.number().min(-90).max(90),
  longitude: z.number().min(-180).max(180),
  altitude: z.number().optional(),
  accuracy: z.number().positive().optional(),
});

/** Validate camera settings */
export const CameraSettingsSchema = z.object({
  iso: z.number().int().positive().optional(),
  aperture: z.number().positive().optional(),
  shutterSpeed: z.string().max(20).optional(),
  focalLength: z.number().positive().optional(),
  flashUsed: z.boolean().optional(),
  whiteBalance: z.string().max(30).optional(),
  resolution: z
    .object({
      width: z.number().int().positive(),
      height: z.number().int().positive(),
    })
    .optional(),
  frameRate: z.number().positive().optional(),
  duration: z.number().positive().optional(),
});

/** Validate capture metadata */
export const CaptureMetadataSchema = z.object({
  capturedAt: z.string().datetime(),
  device: DeviceInfoSchema,
  location: GeoLocationSchema.optional(),
  cameraSettings: CameraSettingsSchema.optional(),
  mediaType: z.nativeEnum(MediaType),
  originalFilename: z.string().min(1).max(255),
  fileSizeBytes: z.number().int().positive(),
  mimeType: z.string().regex(/^(image|video)\/[a-z0-9.+-]+$/),
});

/** Validate registration request body */
export const RegisterRequestSchema = z.object({
  contentHash: z.string().regex(/^[a-f0-9]{64}$/, "Must be a SHA-256 hex hash"),
  metadataHash: z
    .string()
    .regex(/^[a-f0-9]{64}$/, "Must be a SHA-256 hex hash"),
  fingerprint: z.string().regex(/^[a-f0-9]{64}$/, "Must be a SHA-256 hex hash"),
  signature: z.string().regex(/^[a-f0-9]+$/, "Must be hex-encoded"),
  publicKey: z.string().regex(/^[a-f0-9]+$/, "Must be hex-encoded"),
  metadata: CaptureMetadataSchema,
});

/** Validate identity code format */
export const IdentityCodeSchema = z
  .string()
  .regex(
    /^MPROV-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}$/,
    "Invalid identity code format",
  );

/** Validate hash lookup */
export const HashSchema = z
  .string()
  .regex(/^[a-f0-9]{64}$/, "Must be a SHA-256 hex hash");

/** Validate UUID */
export const UuidSchema = z.string().uuid("Must be a valid UUID");
