// Generated by GithubCopilot
/**
 * Mobile Camera Capture Integration — React Native / Expo compatible
 * module for capturing media with provenance data.
 *
 * This module provides the bridge between a smartphone's camera
 * and the media provenance system. It:
 *
 * 1. Captures media via the device camera
 * 2. Extracts device info, GPS coordinates, and camera settings
 * 3. Generates a cryptographic identity on-device
 * 4. Registers the identity with the provenance registry
 *
 * NOTE: This module is designed for React Native. For Node.js
 * testing, use the CaptureSimulator class below.
 *
 * Security: Private keys are stored in device secure storage.
 * The device ID is hashed before inclusion in metadata.
 */

import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import {
  generateKeyPair,
  hashContent,
  hashString,
  computeFingerprint,
  signFingerprint,
  generateMediaId,
  generateIdentityCode,
} from "../core/crypto";
import type {
  CaptureMetadata,
  CameraSettings,
  DeviceInfo,
  GeoLocation,
  KeyPair,
  MediaIdentity,
  MediaType,
} from "../types";

/**
 * Simulated device profile for testing purposes.
 * In production React Native, this data comes from device APIs.
 */
export interface DeviceProfile {
  manufacturer: string;
  model: string;
  osVersion: string;
  deviceId: string; // Will be hashed
  defaultLens: string;
}

/**
 * Capture options when taking a photo or video.
 */
export interface CaptureOptions {
  /** Override GPS location (auto-detected in production) */
  location?: GeoLocation;
  /** Camera lens to use */
  lens?: string;
  /** Camera settings override */
  cameraSettings?: CameraSettings;
}

/**
 * Result of a media capture operation.
 */
export interface CaptureResult {
  /** The raw media bytes */
  mediaBuffer: Buffer;
  /** Complete capture metadata */
  metadata: CaptureMetadata;
  /** Cryptographic identity */
  identity: MediaIdentity;
  /** File path (if saved to disk) */
  savedPath?: string;
}

/**
 * CaptureSimulator — simulates smartphone camera capture
 * for testing the provenance system on desktop/server.
 *
 * In a real React Native app, replace this with:
 * - expo-camera for capture
 * - expo-location for GPS
 * - expo-device for device info
 * - expo-secure-store for key storage
 */
export class CaptureSimulator {
  private device: DeviceProfile;
  private keyPair: KeyPair;
  private outputDir: string;

  constructor(device: DeviceProfile, outputDir?: string) {
    this.device = device;
    this.keyPair = generateKeyPair();
    this.outputDir = outputDir ?? path.join(process.cwd(), "data", "captures");

    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }
  }

  /**
   * Get the device's key pair.
   */
  getKeyPair(): KeyPair {
    return { ...this.keyPair };
  }

  /**
   * Get the device info metadata.
   */
  getDeviceInfo(): DeviceInfo {
    return {
      manufacturer: this.device.manufacturer,
      model: this.device.model,
      osVersion: this.device.osVersion,
      deviceIdHash: hashString(this.device.deviceId),
      cameraLens: this.device.defaultLens,
    };
  }

  /**
   * Simulate capturing an image.
   * In production, this would invoke the device camera.
   *
   * @param imageData - Raw image bytes (simulated capture)
   * @param options - Capture options
   * @returns Complete capture result with identity
   */
  captureImage(imageData: Buffer, options?: CaptureOptions): CaptureResult {
    return this.processCapture(
      imageData,
      "IMAGE" as MediaType,
      "image/jpeg",
      options,
    );
  }

  /**
   * Simulate capturing a video.
   *
   * @param videoData - Raw video bytes (simulated capture)
   * @param options - Capture options
   * @returns Complete capture result with identity
   */
  captureVideo(videoData: Buffer, options?: CaptureOptions): CaptureResult {
    return this.processCapture(
      videoData,
      "VIDEO" as MediaType,
      "video/mp4",
      options,
    );
  }

  /**
   * Capture from an existing file on the device.
   *
   * @param filePath - Path to the media file
   * @param mediaType - IMAGE or VIDEO
   * @param options - Capture options
   * @returns Complete capture result with identity
   */
  captureFromFile(
    filePath: string,
    mediaType: MediaType,
    options?: CaptureOptions,
  ): CaptureResult {
    const data = fs.readFileSync(filePath);
    const ext = path.extname(filePath).toLowerCase();
    const mimeMap: Record<string, string> = {
      ".jpg": "image/jpeg",
      ".jpeg": "image/jpeg",
      ".png": "image/png",
      ".heic": "image/heic",
      ".webp": "image/webp",
      ".mp4": "video/mp4",
      ".mov": "video/quicktime",
      ".avi": "video/x-msvideo",
      ".webm": "video/webm",
    };
    const mimeType = mimeMap[ext] ?? "application/octet-stream";
    return this.processCapture(data, mediaType, mimeType, options);
  }

  /**
   * Core capture processing pipeline.
   */
  private processCapture(
    mediaData: Buffer,
    mediaType: MediaType,
    mimeType: string,
    options?: CaptureOptions,
  ): CaptureResult {
    const now = new Date();
    const filename = `capture_${now.getTime()}.${mimeType.split("/")[1]}`;

    // Build capture metadata
    const metadata: CaptureMetadata = {
      capturedAt: now.toISOString(),
      device: this.getDeviceInfo(),
      location: options?.location ?? this.simulateGps(),
      cameraSettings:
        options?.cameraSettings ?? this.simulateCameraSettings(mediaType),
      mediaType,
      originalFilename: filename,
      fileSizeBytes: mediaData.length,
      mimeType,
    };

    if (options?.lens) {
      metadata.device.cameraLens = options.lens;
    }

    // Generate cryptographic identity
    const contentHash = hashContent(mediaData);
    const canonicalMeta = JSON.stringify(
      metadata,
      Object.keys(metadata).sort(),
    );
    const metadataHash = hashString(canonicalMeta);
    const fingerprint = computeFingerprint(contentHash, metadataHash);
    const signature = signFingerprint(fingerprint, this.keyPair.privateKey);

    const identity: MediaIdentity = {
      mediaId: generateMediaId(),
      contentHash,
      metadataHash,
      fingerprint,
      signature,
      publicKey: this.keyPair.publicKey,
      createdAt: now.toISOString(),
      metadata,
      identityCode: generateIdentityCode(fingerprint),
    };

    // Save media and identity to disk
    const mediaPath = path.join(this.outputDir, filename);
    fs.writeFileSync(mediaPath, mediaData);

    const identityPath = path.join(
      this.outputDir,
      `${path.basename(filename, path.extname(filename))}_identity.json`,
    );
    fs.writeFileSync(identityPath, JSON.stringify(identity, null, 2));

    return {
      mediaBuffer: mediaData,
      metadata,
      identity,
      savedPath: mediaPath,
    };
  }

  /**
   * Simulate GPS location (for testing only).
   * In production, use expo-location or navigator.geolocation.
   */
  private simulateGps(): GeoLocation {
    return {
      latitude: 28.6139 + (Math.random() - 0.5) * 0.01,
      longitude: 77.209 + (Math.random() - 0.5) * 0.01,
      altitude: 200 + Math.random() * 50,
      accuracy: 3 + Math.random() * 10,
    };
  }

  /**
   * Simulate camera settings (for testing only).
   * In production, extract from EXIF data.
   */
  private simulateCameraSettings(mediaType: MediaType): CameraSettings {
    const settings: CameraSettings = {
      iso: [100, 200, 400, 800, 1600][Math.floor(Math.random() * 5)],
      aperture: [1.8, 2.2, 2.8, 4.0][Math.floor(Math.random() * 4)],
      shutterSpeed: ["1/60", "1/125", "1/250", "1/500", "1/1000"][
        Math.floor(Math.random() * 5)
      ],
      focalLength: [24, 26, 28, 35, 50, 77][Math.floor(Math.random() * 6)],
      flashUsed: Math.random() > 0.7,
      whiteBalance: "auto",
      resolution: { width: 4032, height: 3024 },
    };

    if (mediaType === ("VIDEO" as MediaType)) {
      settings.resolution = { width: 3840, height: 2160 };
      settings.frameRate = [24, 30, 60][Math.floor(Math.random() * 3)];
      settings.duration = 5 + Math.random() * 55;
    }

    return settings;
  }
}

/**
 * React Native Integration Guide:
 *
 * ```typescript
 * // In your React Native app:
 * import * as Camera from 'expo-camera';
 * import * as Location from 'expo-location';
 * import * as Device from 'expo-device';
 * import * as SecureStore from 'expo-secure-store';
 * import { MediaProvenanceClient } from 'media-provenance/client';
 *
 * // Initialize client once
 * const storedKeys = await SecureStore.getItemAsync('provenance_keys');
 * const client = new MediaProvenanceClient({
 *   serverUrl: 'https://your-registry.example.com',
 *   keyPair: storedKeys ? JSON.parse(storedKeys) : undefined,
 * });
 *
 * // Save new key pair securely
 * if (!storedKeys) {
 *   await SecureStore.setItemAsync(
 *     'provenance_keys',
 *     JSON.stringify(client.getKeyPair()),
 *   );
 * }
 *
 * // Capture and register
 * async function captureWithProvenance() {
 *   const photo = await Camera.takePictureAsync({ base64: true });
 *   const location = await Location.getCurrentPositionAsync();
 *   const mediaBuffer = Buffer.from(photo.base64, 'base64');
 *
 *   const metadata = {
 *     capturedAt: new Date().toISOString(),
 *     device: {
 *       manufacturer: Device.manufacturer,
 *       model: Device.modelName,
 *       osVersion: `${Device.osName} ${Device.osVersion}`,
 *       deviceIdHash: hashString(Device.osBuildId),
 *     },
 *     location: {
 *       latitude: location.coords.latitude,
 *       longitude: location.coords.longitude,
 *       altitude: location.coords.altitude,
 *       accuracy: location.coords.accuracy,
 *     },
 *     mediaType: 'IMAGE',
 *     originalFilename: `photo_${Date.now()}.jpg`,
 *     fileSizeBytes: mediaBuffer.length,
 *     mimeType: 'image/jpeg',
 *   };
 *
 *   const { identity, registration } = await client.captureAndRegister(
 *     mediaBuffer, metadata
 *   );
 *
 *   // Show identity code to user
 *   Alert.alert('Media Registered', identity.identityCode);
 * }
 * ```
 */
