// Generated by GithubCopilot
/**
 * Media Provenance & Integrity Verification System
 *
 * Core type definitions for media identity, capture metadata,
 * verification results, and registry records.
 *
 * Security: All types enforce required fields for tamper-evident records.
 * Accessibility: Type-safe interfaces reduce runtime errors.
 */

/** Supported media types */
export enum MediaType {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
}

/** Capture device information */
export interface DeviceInfo {
  /** Device manufacturer (e.g., "Apple", "Samsung") */
  manufacturer: string;
  /** Device model (e.g., "iPhone 15 Pro") */
  model: string;
  /** Operating system and version */
  osVersion: string;
  /** Unique device identifier (hashed for privacy) */
  deviceIdHash: string;
  /** Camera lens used (e.g., "wide", "ultrawide", "telephoto") */
  cameraLens?: string;
}

/** GPS coordinates at time of capture */
export interface GeoLocation {
  latitude: number;
  longitude: number;
  altitude?: number;
  accuracy?: number;
}

/** Camera settings at time of capture */
export interface CameraSettings {
  iso?: number;
  aperture?: number;
  shutterSpeed?: string;
  focalLength?: number;
  flashUsed?: boolean;
  whiteBalance?: string;
  resolution?: { width: number; height: number };
  frameRate?: number; // For video
  duration?: number; // For video, in seconds
}

/**
 * Complete capture metadata — everything about HOW and WHERE
 * the media was captured, excluding the media content itself.
 */
export interface CaptureMetadata {
  /** When the media was captured (ISO 8601) */
  capturedAt: string;
  /** Device that captured the media */
  device: DeviceInfo;
  /** GPS location at time of capture */
  location?: GeoLocation;
  /** Camera settings used */
  cameraSettings?: CameraSettings;
  /** Type of media captured */
  mediaType: MediaType;
  /** Original filename on device */
  originalFilename: string;
  /** File size in bytes */
  fileSizeBytes: number;
  /** MIME type (e.g., "image/jpeg", "video/mp4") */
  mimeType: string;
}

/**
 * The cryptographic identity assigned to a media capture.
 * This is the core record that proves provenance and integrity.
 */
export interface MediaIdentity {
  /** Unique Media ID (UUID v4) */
  mediaId: string;
  /** SHA-256 hash of the raw media bytes (hex) */
  contentHash: string;
  /** SHA-256 hash of capture metadata JSON (hex) */
  metadataHash: string;
  /** Combined fingerprint: SHA-256(contentHash + metadataHash) */
  fingerprint: string;
  /** Ed25519 digital signature of the fingerprint */
  signature: string;
  /** Ed25519 public key used for signing (hex) */
  publicKey: string;
  /** When the identity was created (ISO 8601) */
  createdAt: string;
  /** Capture metadata */
  metadata: CaptureMetadata;
  /** Short human-readable identity code */
  identityCode: string;
}

/** Record stored in the registry */
export interface RegistryRecord {
  mediaId: string;
  contentHash: string;
  metadataHash: string;
  fingerprint: string;
  signature: string;
  publicKey: string;
  createdAt: string;
  registeredAt: string;
  metadata: CaptureMetadata;
  identityCode: string;
  /** Whether the record has been verified at least once */
  verified: boolean;
  /** Number of times this media has been verified */
  verificationCount: number;
}

/** Result of a verification check */
export interface VerificationResult {
  /** Whether the media is authentic and untampered */
  isAuthentic: boolean;
  /** Whether the content hash matches a registered record */
  contentMatch: boolean;
  /** Whether the digital signature is valid */
  signatureValid: boolean;
  /** Whether metadata integrity is intact */
  metadataIntact: boolean;
  /** The matching registry record, if found */
  registryRecord?: RegistryRecord;
  /** Human-readable verification summary */
  summary: string;
  /** Verification timestamp */
  verifiedAt: string;
  /** Any warnings or notes */
  warnings: string[];
}

/** Key pair for signing */
export interface KeyPair {
  publicKey: string;
  privateKey: string;
}

/** API response wrapper */
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  timestamp: string;
}
