// Generated by GithubCopilot
/**
 * Cryptographic utilities for media identity generation and verification.
 *
 * Uses Node.js built-in crypto module:
 * - SHA-256 for content hashing (tamper detection)
 * - Ed25519 for digital signatures (authenticity proof)
 * - UUID v4 for unique media identifiers
 *
 * Security: Uses only vetted, modern cryptographic primitives.
 * No hardcoded secrets — keys are generated per-device.
 */

import * as crypto from "node:crypto";
import { v4 as uuidv4 } from "uuid";
import type { KeyPair } from "../types";

/**
 * Compute SHA-256 hash of a Buffer (raw media bytes).
 * @param data - Raw binary data to hash
 * @returns Hex-encoded SHA-256 digest
 */
export function hashContent(data: Buffer): string {
  return crypto.createHash("sha256").update(data).digest("hex");
}

/**
 * Compute SHA-256 hash of a string (e.g., JSON metadata).
 * @param text - String data to hash
 * @returns Hex-encoded SHA-256 digest
 */
export function hashString(text: string): string {
  return crypto.createHash("sha256").update(text, "utf8").digest("hex");
}

/**
 * Compute the combined fingerprint from content hash and metadata hash.
 * fingerprint = SHA-256(contentHash + metadataHash)
 *
 * This binds the media content to its capture context,
 * making it impossible to swap metadata between captures.
 *
 * @param contentHash - SHA-256 hash of media bytes
 * @param metadataHash - SHA-256 hash of metadata JSON
 * @returns Hex-encoded fingerprint
 */
export function computeFingerprint(
  contentHash: string,
  metadataHash: string,
): string {
  return hashString(contentHash + metadataHash);
}

/**
 * Generate a new Ed25519 key pair for signing media identities.
 * Each device should generate and securely store one key pair.
 *
 * @returns KeyPair with hex-encoded public and private keys
 */
export function generateKeyPair(): KeyPair {
  const { publicKey, privateKey } = crypto.generateKeyPairSync("ed25519", {
    publicKeyEncoding: { type: "spki", format: "der" },
    privateKeyEncoding: { type: "pkcs8", format: "der" },
  });

  return {
    publicKey: publicKey.toString("hex"),
    privateKey: privateKey.toString("hex"),
  };
}

/**
 * Sign a fingerprint using Ed25519 private key.
 * The signature proves that the identity was created by the holder
 * of the corresponding private key (the capture device).
 *
 * @param fingerprint - The combined fingerprint to sign
 * @param privateKeyHex - Hex-encoded Ed25519 private key (PKCS8 DER)
 * @returns Hex-encoded signature
 */
export function signFingerprint(
  fingerprint: string,
  privateKeyHex: string,
): string {
  const privateKeyDer = Buffer.from(privateKeyHex, "hex");
  const privateKey = crypto.createPrivateKey({
    key: privateKeyDer,
    format: "der",
    type: "pkcs8",
  });

  const signature = crypto.sign(
    null,
    Buffer.from(fingerprint, "utf8"),
    privateKey,
  );
  return signature.toString("hex");
}

/**
 * Verify an Ed25519 signature against a fingerprint and public key.
 * Anyone with the public key can verify authenticity.
 *
 * @param fingerprint - The fingerprint that was signed
 * @param signatureHex - Hex-encoded signature to verify
 * @param publicKeyHex - Hex-encoded Ed25519 public key (SPKI DER)
 * @returns true if the signature is valid
 */
export function verifySignature(
  fingerprint: string,
  signatureHex: string,
  publicKeyHex: string,
): boolean {
  try {
    const publicKeyDer = Buffer.from(publicKeyHex, "hex");
    const publicKey = crypto.createPublicKey({
      key: publicKeyDer,
      format: "der",
      type: "spki",
    });

    const signature = Buffer.from(signatureHex, "hex");
    return crypto.verify(
      null,
      Buffer.from(fingerprint, "utf8"),
      publicKey,
      signature,
    );
  } catch {
    return false;
  }
}

/**
 * Generate a unique Media ID using UUID v4.
 * @returns UUID v4 string
 */
export function generateMediaId(): string {
  return uuidv4();
}

/**
 * Generate a short, human-readable identity code from the fingerprint.
 * Format: MPROV-XXXX-XXXX-XXXX (16 hex chars from fingerprint)
 *
 * @param fingerprint - Full hex fingerprint
 * @returns Short identity code
 */
export function generateIdentityCode(fingerprint: string): string {
  const short = fingerprint.substring(0, 12).toUpperCase();
  return `MPROV-${short.slice(0, 4)}-${short.slice(4, 8)}-${short.slice(8, 12)}`;
}

/**
 * Generate a cryptographically secure random token.
 * @param bytes - Number of random bytes (default: 32)
 * @returns Hex-encoded random token
 */
export function generateSecureToken(bytes: number = 32): string {
  return crypto.randomBytes(bytes).toString("hex");
}
