// Generated by GithubCopilot
/**
 * Media Identity Generator — the core engine that creates a
 * cryptographic identity for each captured image or video.
 *
 * Flow:
 * 1. Receive raw media bytes + capture metadata
 * 2. Hash the content (SHA-256)
 * 3. Hash the metadata (SHA-256 of canonical JSON)
 * 4. Compute combined fingerprint
 * 5. Sign the fingerprint with device's Ed25519 private key
 * 6. Generate unique Media ID and identity code
 * 7. Return the complete MediaIdentity record
 *
 * Security: Content and metadata are cryptographically bound together.
 * Changing even 1 bit of the media or metadata invalidates the identity.
 */

import {
  hashContent,
  hashString,
  computeFingerprint,
  signFingerprint,
  generateMediaId,
  generateIdentityCode,
} from "./crypto";
import type { CaptureMetadata, MediaIdentity } from "../types";

/**
 * Canonicalize metadata to ensure consistent hashing.
 * Sorts keys deterministically so the same metadata always
 * produces the same hash regardless of property order.
 *
 * @param metadata - Capture metadata object
 * @returns Deterministic JSON string
 */
function canonicalizeMetadata(metadata: CaptureMetadata): string {
  return JSON.stringify(metadata, Object.keys(metadata).sort());
}

/**
 * Generate a complete cryptographic identity for a media capture.
 *
 * @param mediaBuffer - Raw bytes of the captured image or video
 * @param metadata - Capture metadata (device, location, settings, etc.)
 * @param privateKeyHex - Device's Ed25519 private key (hex, PKCS8 DER)
 * @param publicKeyHex - Device's Ed25519 public key (hex, SPKI DER)
 * @returns Complete MediaIdentity record
 */
export function generateMediaIdentity(
  mediaBuffer: Buffer,
  metadata: CaptureMetadata,
  privateKeyHex: string,
  publicKeyHex: string,
): MediaIdentity {
  // Step 1: Hash the raw media content
  const contentHash = hashContent(mediaBuffer);

  // Step 2: Hash the capture metadata (canonical form)
  const canonicalMeta = canonicalizeMetadata(metadata);
  const metadataHash = hashString(canonicalMeta);

  // Step 3: Compute combined fingerprint binding content to metadata
  const fingerprint = computeFingerprint(contentHash, metadataHash);

  // Step 4: Sign the fingerprint with device's private key
  const signature = signFingerprint(fingerprint, privateKeyHex);

  // Step 5: Generate unique identifiers
  const mediaId = generateMediaId();
  const identityCode = generateIdentityCode(fingerprint);
  const createdAt = new Date().toISOString();

  // Step 6: Assemble and return the identity record
  return {
    mediaId,
    contentHash,
    metadataHash,
    fingerprint,
    signature,
    publicKey: publicKeyHex,
    createdAt,
    metadata,
    identityCode,
  };
}

/**
 * Recompute the content hash of a media file for verification.
 * Used by verifiers who have the original media.
 *
 * @param mediaBuffer - Raw bytes of the media to verify
 * @returns SHA-256 hex hash
 */
export function recomputeContentHash(mediaBuffer: Buffer): string {
  return hashContent(mediaBuffer);
}

/**
 * Recompute the metadata hash for verification.
 *
 * @param metadata - Capture metadata to verify
 * @returns SHA-256 hex hash
 */
export function recomputeMetadataHash(metadata: CaptureMetadata): string {
  const canonical = canonicalizeMetadata(metadata);
  return hashString(canonical);
}
