// Generated by GithubCopilot
/**
 * Verification Engine — allows anyone to verify the authenticity
 * and integrity of a media capture against registry records.
 *
 * Verification checks:
 * 1. Content hash match — has the media been altered?
 * 2. Metadata integrity — has the metadata been tampered with?
 * 3. Fingerprint validity — are content and metadata properly bound?
 * 4. Digital signature — was this signed by the original capture device?
 *
 * Security: All checks are independent; partial tampering is detected.
 */

import { computeFingerprint, verifySignature } from "./crypto";
import { recomputeContentHash, recomputeMetadataHash } from "./identity";
import type {
  CaptureMetadata,
  RegistryRecord,
  VerificationResult,
} from "../types";

/**
 * Verify a media file against a registry record.
 *
 * @param mediaBuffer - Raw bytes of the media to verify
 * @param record - The registry record to verify against
 * @returns Detailed verification result
 */
export function verifyMedia(
  mediaBuffer: Buffer,
  record: RegistryRecord,
): VerificationResult {
  const warnings: string[] = [];
  const verifiedAt = new Date().toISOString();

  // Check 1: Content hash match
  const recomputedContentHash = recomputeContentHash(mediaBuffer);
  const contentMatch = recomputedContentHash === record.contentHash;

  if (!contentMatch) {
    warnings.push(
      "Content hash mismatch — the media file has been modified since capture.",
    );
  }

  // Check 2: Metadata integrity
  const recomputedMetadataHash = recomputeMetadataHash(record.metadata);
  const metadataIntact = recomputedMetadataHash === record.metadataHash;

  if (!metadataIntact) {
    warnings.push(
      "Metadata hash mismatch — capture metadata may have been tampered with.",
    );
  }

  // Check 3: Fingerprint validity
  const recomputedFingerprint = computeFingerprint(
    record.contentHash,
    record.metadataHash,
  );
  const fingerprintValid = recomputedFingerprint === record.fingerprint;

  if (!fingerprintValid) {
    warnings.push(
      "Fingerprint mismatch — content and metadata binding is broken.",
    );
  }

  // Check 4: Digital signature
  const signatureValid = verifySignature(
    record.fingerprint,
    record.signature,
    record.publicKey,
  );

  if (!signatureValid) {
    warnings.push(
      "Digital signature invalid — the identity may not have been created by the claimed device.",
    );
  }

  // Determine overall authenticity
  const isAuthentic =
    contentMatch && metadataIntact && fingerprintValid && signatureValid;

  // Generate human-readable summary
  let summary: string;
  if (isAuthentic) {
    summary =
      `✅ VERIFIED — This media is authentic and unmodified. ` +
      `Captured on ${record.metadata.device.manufacturer} ${record.metadata.device.model} ` +
      `at ${record.metadata.capturedAt}. Identity: ${record.identityCode}`;
  } else {
    const failedChecks: string[] = [];
    if (!contentMatch) failedChecks.push("content modified");
    if (!signatureValid) failedChecks.push("invalid signature");
    if (!metadataIntact) failedChecks.push("metadata tampered");
    if (!fingerprintValid) failedChecks.push("binding broken");
    summary = `❌ VERIFICATION FAILED — Issues detected: ${failedChecks.join(", ")}.`;
  }

  return {
    isAuthentic,
    contentMatch,
    signatureValid,
    metadataIntact,
    registryRecord: record,
    summary,
    verifiedAt,
    warnings,
  };
}

/**
 * Quick verification — check only the content hash against a known hash.
 * Useful for fast screening without full record lookup.
 *
 * @param mediaBuffer - Raw bytes of the media
 * @param expectedHash - Expected SHA-256 content hash
 * @returns true if the media is unmodified
 */
export function quickVerifyContent(
  mediaBuffer: Buffer,
  expectedHash: string,
): boolean {
  const actualHash = recomputeContentHash(mediaBuffer);
  return actualHash === expectedHash;
}

/**
 * Verify only the digital signature of an identity record.
 * Useful for checking authenticity without having the original media.
 *
 * @param fingerprint - The fingerprint that was signed
 * @param signature - The digital signature (hex)
 * @param publicKey - The signer's public key (hex)
 * @returns true if the signature is valid
 */
export function verifyIdentitySignature(
  fingerprint: string,
  signature: string,
  publicKey: string,
): boolean {
  return verifySignature(fingerprint, signature, publicKey);
}
