// Generated by GithubCopilot
/**
 * SQLite-based Media Identity Registry — persistent storage for
 * all registered media identity records.
 *
 * Uses better-sqlite3 for synchronous, high-performance SQLite.
 * Resource efficiency: SQLite requires no separate server process.
 *
 * Security: Uses parameterized queries to prevent SQL injection.
 */

import Database from "better-sqlite3";
import * as path from "node:path";
import * as fs from "node:fs";
import type { MediaIdentity, RegistryRecord, CaptureMetadata } from "../types";

const DEFAULT_DB_PATH = path.join(process.cwd(), "data", "media-registry.db");

export class MediaRegistry {
  private db: Database.Database;

  /**
   * Initialize the registry database.
   * @param dbPath - Path to the SQLite database file
   */
  constructor(dbPath: string = DEFAULT_DB_PATH) {
    // Ensure directory exists
    const dir = path.dirname(dbPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    this.db = new Database(dbPath);
    this.db.pragma("journal_mode = WAL"); // Better concurrent read performance
    this.db.pragma("foreign_keys = ON");
    this.initializeSchema();
  }

  /**
   * Create tables if they don't exist.
   */
  private initializeSchema(): void {
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS media_identities (
        media_id TEXT PRIMARY KEY,
        content_hash TEXT NOT NULL,
        metadata_hash TEXT NOT NULL,
        fingerprint TEXT NOT NULL UNIQUE,
        signature TEXT NOT NULL,
        public_key TEXT NOT NULL,
        created_at TEXT NOT NULL,
        registered_at TEXT NOT NULL DEFAULT (datetime('now')),
        metadata_json TEXT NOT NULL,
        identity_code TEXT NOT NULL,
        verified INTEGER NOT NULL DEFAULT 0,
        verification_count INTEGER NOT NULL DEFAULT 0
      );

      CREATE INDEX IF NOT EXISTS idx_content_hash
        ON media_identities(content_hash);

      CREATE INDEX IF NOT EXISTS idx_fingerprint
        ON media_identities(fingerprint);

      CREATE INDEX IF NOT EXISTS idx_identity_code
        ON media_identities(identity_code);

      CREATE INDEX IF NOT EXISTS idx_created_at
        ON media_identities(created_at);

      CREATE INDEX IF NOT EXISTS idx_public_key
        ON media_identities(public_key);

      CREATE TABLE IF NOT EXISTS verification_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        media_id TEXT NOT NULL,
        verified_at TEXT NOT NULL DEFAULT (datetime('now')),
        is_authentic INTEGER NOT NULL,
        content_match INTEGER NOT NULL,
        signature_valid INTEGER NOT NULL,
        metadata_intact INTEGER NOT NULL,
        verifier_ip TEXT,
        FOREIGN KEY (media_id) REFERENCES media_identities(media_id)
      );

      CREATE INDEX IF NOT EXISTS idx_verification_media_id
        ON verification_log(media_id);
    `);
  }

  /**
   * Register a new media identity in the registry.
   * @param identity - The media identity to register
   * @returns The complete registry record
   */
  register(identity: MediaIdentity): RegistryRecord {
    const registeredAt = new Date().toISOString();
    const metadataJson = JSON.stringify(identity.metadata);

    const stmt = this.db.prepare(`
      INSERT INTO media_identities (
        media_id, content_hash, metadata_hash, fingerprint,
        signature, public_key, created_at, registered_at,
        metadata_json, identity_code
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);

    stmt.run(
      identity.mediaId,
      identity.contentHash,
      identity.metadataHash,
      identity.fingerprint,
      identity.signature,
      identity.publicKey,
      identity.createdAt,
      registeredAt,
      metadataJson,
      identity.identityCode,
    );

    return {
      ...identity,
      registeredAt,
      verified: false,
      verificationCount: 0,
    };
  }

  /**
   * Look up a registry record by content hash.
   * Used when someone submits media for verification.
   *
   * @param contentHash - SHA-256 hash of the media content
   * @returns Matching registry record, or null
   */
  findByContentHash(contentHash: string): RegistryRecord | null {
    const stmt = this.db.prepare(
      "SELECT * FROM media_identities WHERE content_hash = ?",
    );
    const row = stmt.get(contentHash) as Record<string, unknown> | undefined;
    return row ? this.rowToRecord(row) : null;
  }

  /**
   * Look up a registry record by fingerprint.
   *
   * @param fingerprint - The combined fingerprint
   * @returns Matching registry record, or null
   */
  findByFingerprint(fingerprint: string): RegistryRecord | null {
    const stmt = this.db.prepare(
      "SELECT * FROM media_identities WHERE fingerprint = ?",
    );
    const row = stmt.get(fingerprint) as Record<string, unknown> | undefined;
    return row ? this.rowToRecord(row) : null;
  }

  /**
   * Look up a registry record by media ID.
   *
   * @param mediaId - The unique media ID (UUID)
   * @returns Matching registry record, or null
   */
  findByMediaId(mediaId: string): RegistryRecord | null {
    const stmt = this.db.prepare(
      "SELECT * FROM media_identities WHERE media_id = ?",
    );
    const row = stmt.get(mediaId) as Record<string, unknown> | undefined;
    return row ? this.rowToRecord(row) : null;
  }

  /**
   * Look up a registry record by human-readable identity code.
   *
   * @param identityCode - Short identity code (MPROV-XXXX-XXXX-XXXX)
   * @returns Matching registry record, or null
   */
  findByIdentityCode(identityCode: string): RegistryRecord | null {
    const stmt = this.db.prepare(
      "SELECT * FROM media_identities WHERE identity_code = ?",
    );
    const row = stmt.get(identityCode) as Record<string, unknown> | undefined;
    return row ? this.rowToRecord(row) : null;
  }

  /**
   * Find all media identities registered by a specific device (public key).
   *
   * @param publicKey - The device's public key (hex)
   * @param limit - Maximum results (default: 100)
   * @returns Array of registry records
   */
  findByDevice(publicKey: string, limit: number = 100): RegistryRecord[] {
    const stmt = this.db.prepare(
      "SELECT * FROM media_identities WHERE public_key = ? ORDER BY created_at DESC LIMIT ?",
    );
    const rows = stmt.all(publicKey, limit) as Record<string, unknown>[];
    return rows.map((row) => this.rowToRecord(row));
  }

  /**
   * Increment the verification count for a media identity.
   *
   * @param mediaId - The media ID to update
   * @param isAuthentic - Whether the verification passed
   * @param verifierIp - IP of the verifier (optional, for audit)
   */
  logVerification(
    mediaId: string,
    isAuthentic: boolean,
    contentMatch: boolean,
    signatureValid: boolean,
    metadataIntact: boolean,
    verifierIp?: string,
  ): void {
    const updateStmt = this.db.prepare(`
      UPDATE media_identities
      SET verified = 1, verification_count = verification_count + 1
      WHERE media_id = ?
    `);
    updateStmt.run(mediaId);

    const logStmt = this.db.prepare(`
      INSERT INTO verification_log (
        media_id, is_authentic, content_match, signature_valid,
        metadata_intact, verifier_ip
      ) VALUES (?, ?, ?, ?, ?, ?)
    `);
    logStmt.run(
      mediaId,
      isAuthentic ? 1 : 0,
      contentMatch ? 1 : 0,
      signatureValid ? 1 : 0,
      metadataIntact ? 1 : 0,
      verifierIp ?? null,
    );
  }

  /**
   * Get total count of registered media identities.
   */
  getCount(): number {
    const row = this.db
      .prepare("SELECT COUNT(*) as count FROM media_identities")
      .get() as { count: number };
    return row.count;
  }

  /**
   * Get recent registrations.
   *
   * @param limit - Number of records to return
   * @returns Array of recent registry records
   */
  getRecent(limit: number = 20): RegistryRecord[] {
    const stmt = this.db.prepare(
      "SELECT * FROM media_identities ORDER BY registered_at DESC LIMIT ?",
    );
    const rows = stmt.all(limit) as Record<string, unknown>[];
    return rows.map((row) => this.rowToRecord(row));
  }

  /**
   * Close the database connection.
   * Call this when shutting down the application.
   */
  close(): void {
    this.db.close();
  }

  /**
   * Convert a database row to a RegistryRecord.
   */
  private rowToRecord(row: Record<string, unknown>): RegistryRecord {
    return {
      mediaId: row.media_id as string,
      contentHash: row.content_hash as string,
      metadataHash: row.metadata_hash as string,
      fingerprint: row.fingerprint as string,
      signature: row.signature as string,
      publicKey: row.public_key as string,
      createdAt: row.created_at as string,
      registeredAt: row.registered_at as string,
      metadata: JSON.parse(row.metadata_json as string) as CaptureMetadata,
      identityCode: row.identity_code as string,
      verified: (row.verified as number) === 1,
      verificationCount: row.verification_count as number,
    };
  }
}
