// Generated by GithubCopilot
/**
 * Demo Script — demonstrates the full media provenance lifecycle:
 *
 * 1. Device key pair generation
 * 2. Simulated camera capture with metadata
 * 3. Cryptographic identity generation
 * 4. Registration in the registry
 * 5. Verification of authentic media (passes)
 * 6. Verification of tampered media (fails)
 * 7. Lookup by identity code
 *
 * Run: npx ts-node src/demo.ts
 */

import * as crypto from "node:crypto";
import { CaptureSimulator, DeviceProfile } from "./capture";
import { MediaRegistry } from "./storage";
import { verifyMedia, verifyIdentitySignature } from "./core/verification";
import { hashContent } from "./core/crypto";
import { MediaType } from "./types";

function printSeparator(title: string): void {
  console.log("\n" + "═".repeat(60));
  console.log(`  ${title}`);
  console.log("═".repeat(60));
}

async function runDemo(): Promise<void> {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║    MEDIA PROVENANCE & INTEGRITY VERIFICATION SYSTEM         ║
║    ───────────────────────────────────────────────           ║
║    Demo: Full Lifecycle Walkthrough                          ║
╚══════════════════════════════════════════════════════════════╝
  `);

  // ─── Step 1: Initialize Device ───────────────────────────────
  printSeparator("STEP 1: Device Initialization");

  const device: DeviceProfile = {
    manufacturer: "Apple",
    model: "iPhone 15 Pro",
    osVersion: "iOS 17.2",
    deviceId: "UNIQUE-DEVICE-SERIAL-12345",
    defaultLens: "wide",
  };

  const simulator = new CaptureSimulator(device);
  const keyPair = simulator.getKeyPair();

  console.log(`✓ Device: ${device.manufacturer} ${device.model}`);
  console.log(`✓ OS: ${device.osVersion}`);
  console.log(`✓ Public Key: ${keyPair.publicKey.substring(0, 40)}...`);
  console.log(`✓ Private Key: [SECURED ON DEVICE — never transmitted]`);

  // ─── Step 2: Initialize Registry ────────────────────────────
  printSeparator("STEP 2: Registry Initialization");

  const registry = new MediaRegistry();
  console.log(`✓ SQLite registry initialized`);
  console.log(`✓ Current entries: ${registry.getCount()}`);

  // ─── Step 3: Simulate Camera Capture ────────────────────────
  printSeparator("STEP 3: Simulated Camera Capture");

  // Create a simulated image (random bytes representing a photo)
  const simulatedPhoto = crypto.randomBytes(1024 * 100); // 100KB "photo"
  console.log(`✓ Simulated photo capture: ${simulatedPhoto.length} bytes`);

  const captureResult = simulator.captureImage(simulatedPhoto, {
    location: {
      latitude: 28.6139,
      longitude: 77.209,
      altitude: 216,
      accuracy: 5,
    },
  });

  console.log(`✓ Captured at: ${captureResult.metadata.capturedAt}`);
  console.log(
    `✓ Location: ${captureResult.metadata.location?.latitude}, ${captureResult.metadata.location?.longitude}`,
  );
  console.log(
    `✓ Camera: ISO ${captureResult.metadata.cameraSettings?.iso}, f/${captureResult.metadata.cameraSettings?.aperture}`,
  );
  console.log(`✓ File saved: ${captureResult.savedPath}`);

  // ─── Step 4: View Cryptographic Identity ────────────────────
  printSeparator("STEP 4: Cryptographic Identity");

  const identity = captureResult.identity;
  console.log(`✓ Media ID:       ${identity.mediaId}`);
  console.log(`✓ Identity Code:  ${identity.identityCode}`);
  console.log(`✓ Content Hash:   ${identity.contentHash.substring(0, 32)}...`);
  console.log(`✓ Metadata Hash:  ${identity.metadataHash.substring(0, 32)}...`);
  console.log(`✓ Fingerprint:    ${identity.fingerprint.substring(0, 32)}...`);
  console.log(`✓ Signature:      ${identity.signature.substring(0, 32)}...`);
  console.log(`✓ Public Key:     ${identity.publicKey.substring(0, 32)}...`);

  // ─── Step 5: Register in the Registry ───────────────────────
  printSeparator("STEP 5: Registration");

  const record = registry.register(identity);
  console.log(`✓ Registered at:  ${record.registeredAt}`);
  console.log(`✓ Registry count: ${registry.getCount()}`);

  // ─── Step 6: Capture and register a video ────────────────────
  printSeparator("STEP 6: Video Capture & Registration");

  const simulatedVideo = crypto.randomBytes(1024 * 500); // 500KB "video"
  const videoCapture = simulator.captureVideo(simulatedVideo, {
    location: {
      latitude: 28.6139,
      longitude: 77.209,
      altitude: 216,
      accuracy: 5,
    },
  });
  const videoRecord = registry.register(videoCapture.identity);

  console.log(`✓ Video captured and registered`);
  console.log(`✓ Identity Code:  ${videoCapture.identity.identityCode}`);
  console.log(
    `✓ Duration:       ${videoCapture.metadata.cameraSettings?.duration?.toFixed(1)}s`,
  );
  console.log(
    `✓ Resolution:     ${videoCapture.metadata.cameraSettings?.resolution?.width}x${videoCapture.metadata.cameraSettings?.resolution?.height}`,
  );
  console.log(`✓ Registry count: ${registry.getCount()}`);

  // ─── Step 7: Verify AUTHENTIC media ─────────────────────────
  printSeparator("STEP 7: Verify AUTHENTIC Media (should PASS)");

  const verifyOriginal = verifyMedia(simulatedPhoto, record);
  console.log(`✓ Is Authentic:      ${verifyOriginal.isAuthentic}`);
  console.log(`✓ Content Match:     ${verifyOriginal.contentMatch}`);
  console.log(`✓ Signature Valid:   ${verifyOriginal.signatureValid}`);
  console.log(`✓ Metadata Intact:   ${verifyOriginal.metadataIntact}`);
  console.log(`✓ Summary: ${verifyOriginal.summary}`);

  // ─── Step 8: Verify TAMPERED media ──────────────────────────
  printSeparator("STEP 8: Verify TAMPERED Media (should FAIL)");

  // Modify just 1 byte of the original photo
  const tamperedPhoto = Buffer.from(simulatedPhoto);
  tamperedPhoto[0] = (tamperedPhoto[0]! + 1) % 256;

  const verifyTampered = verifyMedia(tamperedPhoto, record);
  console.log(`✗ Is Authentic:      ${verifyTampered.isAuthentic}`);
  console.log(`✗ Content Match:     ${verifyTampered.contentMatch}`);
  console.log(
    `✓ Signature Valid:   ${verifyTampered.signatureValid} (signature itself is fine)`,
  );
  console.log(
    `✓ Metadata Intact:   ${verifyTampered.metadataIntact} (metadata unchanged)`,
  );
  console.log(`✗ Summary: ${verifyTampered.summary}`);
  if (verifyTampered.warnings.length > 0) {
    console.log(`  Warnings:`);
    verifyTampered.warnings.forEach((w) => console.log(`    ⚠ ${w}`));
  }

  // ─── Step 9: Lookup by identity code ────────────────────────
  printSeparator("STEP 9: Public Lookup by Identity Code");

  const lookedUp = registry.findByIdentityCode(identity.identityCode);
  if (lookedUp) {
    console.log(`✓ Found record for ${identity.identityCode}`);
    console.log(
      `  Device:    ${lookedUp.metadata.device.manufacturer} ${lookedUp.metadata.device.model}`,
    );
    console.log(`  Captured:  ${lookedUp.metadata.capturedAt}`);
    console.log(`  Verified:  ${lookedUp.verificationCount} times`);
  }

  // ─── Step 10: Signature-only verification ───────────────────
  printSeparator("STEP 10: Signature-Only Verification (no media needed)");

  const sigValid = verifyIdentitySignature(
    record.fingerprint,
    record.signature,
    record.publicKey,
  );
  console.log(`✓ Signature valid: ${sigValid}`);
  console.log(`  (Anyone can verify without the original media file)`);

  // ─── Step 11: Device history ────────────────────────────────
  printSeparator("STEP 11: Device Capture History");

  const deviceRecords = registry.findByDevice(keyPair.publicKey);
  console.log(`✓ Total captures by this device: ${deviceRecords.length}`);
  deviceRecords.forEach((r, i) => {
    console.log(
      `  ${i + 1}. ${r.identityCode} — ${r.metadata.mediaType} — ${r.metadata.capturedAt}`,
    );
  });

  // ─── Summary ────────────────────────────────────────────────
  printSeparator("DEMO COMPLETE");

  console.log(`
  The Media Provenance system provides:

  1. UNIQUE IDENTITY    — Every capture gets a UUID + cryptographic fingerprint
  2. INTEGRITY PROOF    — SHA-256 hash detects even 1-bit changes
  3. AUTHENTICITY       — Ed25519 signature proves capture device origin
  4. CONTEXT BINDING    — Metadata (time, GPS, device) is cryptographically
                          bound to the content
  5. PUBLIC VERIFICATION — Anyone can verify using the identity code,
                           content hash, or by uploading the media
  6. TAMPER DETECTION   — Modified media fails verification instantly
  7. DEVICE HISTORY     — Complete audit trail per device

  To start the Registry API server:
    npx ts-node src/server/index.ts

  Then use the REST API or client SDK to register and verify media.
  `);

  // Cleanup
  registry.close();
}

// Run the demo
runDemo().catch(console.error);
