// Generated by GithubCopilot
/**
 * Media Provenance Client SDK — used by mobile apps and desktop
 * tools to capture, sign, register, and verify media.
 *
 * This is the main interface for integrating media provenance
 * into any application (React Native, Flutter, Electron, etc.).
 *
 * Security: Private key never leaves the device. Only the
 * public key, hashes, and signatures are sent to the server.
 */

import * as fs from "node:fs";
import {
  generateKeyPair,
  hashContent,
  hashString,
  computeFingerprint,
  signFingerprint,
  generateMediaId,
  generateIdentityCode,
} from "../core/crypto";
import { verifyMedia } from "../core/verification";
import type {
  KeyPair,
  CaptureMetadata,
  MediaIdentity,
  RegistryRecord,
  VerificationResult,
  ApiResponse,
} from "../types";

/**
 * Client configuration
 */
export interface ClientConfig {
  /** URL of the Media Provenance Registry server */
  serverUrl: string;
  /** Device key pair (generate once, store securely on device) */
  keyPair?: KeyPair;
  /** Request timeout in ms (default: 30000) */
  timeout?: number;
}

/**
 * Media Provenance Client — integrate into mobile/desktop apps
 * to capture and verify media provenance.
 */
export class MediaProvenanceClient {
  private serverUrl: string;
  private keyPair: KeyPair;
  private timeout: number;

  constructor(config: ClientConfig) {
    this.serverUrl = config.serverUrl.replace(/\/$/, "");
    this.keyPair = config.keyPair ?? generateKeyPair();
    this.timeout = config.timeout ?? 30_000;
  }

  /**
   * Get the device's public key (safe to share/publish).
   */
  getPublicKey(): string {
    return this.keyPair.publicKey;
  }

  /**
   * Get the full key pair (store securely; never send private key).
   */
  getKeyPair(): KeyPair {
    return { ...this.keyPair };
  }

  /**
   * Generate an identity for a captured media file on-device.
   * This performs all cryptographic operations locally.
   *
   * @param mediaBuffer - Raw bytes of the captured media
   * @param metadata - Capture metadata
   * @returns The signed media identity
   */
  createIdentity(
    mediaBuffer: Buffer,
    metadata: CaptureMetadata,
  ): MediaIdentity {
    const contentHash = hashContent(mediaBuffer);

    const canonicalMeta = JSON.stringify(
      metadata,
      Object.keys(metadata).sort(),
    );
    const metadataHash = hashString(canonicalMeta);

    const fingerprint = computeFingerprint(contentHash, metadataHash);
    const signature = signFingerprint(fingerprint, this.keyPair.privateKey);

    return {
      mediaId: generateMediaId(),
      contentHash,
      metadataHash,
      fingerprint,
      signature,
      publicKey: this.keyPair.publicKey,
      createdAt: new Date().toISOString(),
      metadata,
      identityCode: generateIdentityCode(fingerprint),
    };
  }

  /**
   * Create identity from a file path (convenience method).
   *
   * @param filePath - Path to the media file
   * @param metadata - Capture metadata
   * @returns The signed media identity
   */
  createIdentityFromFile(
    filePath: string,
    metadata: CaptureMetadata,
  ): MediaIdentity {
    const mediaBuffer = fs.readFileSync(filePath);
    return this.createIdentity(mediaBuffer, metadata);
  }

  /**
   * Register a media identity with the remote registry server.
   *
   * @param identity - The media identity to register
   * @returns Registry record from the server
   */
  async register(
    identity: MediaIdentity,
  ): Promise<ApiResponse<RegistryRecord>> {
    const response = await fetch(`${this.serverUrl}/api/v1/register`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contentHash: identity.contentHash,
        metadataHash: identity.metadataHash,
        fingerprint: identity.fingerprint,
        signature: identity.signature,
        publicKey: identity.publicKey,
        metadata: identity.metadata,
      }),
      signal: AbortSignal.timeout(this.timeout),
    });

    return response.json() as Promise<ApiResponse<RegistryRecord>>;
  }

  /**
   * Capture + Sign + Register in one call.
   * Convenience method for the full flow.
   *
   * @param mediaBuffer - Raw bytes of the captured media
   * @param metadata - Capture metadata
   * @returns Registry record from the server
   */
  async captureAndRegister(
    mediaBuffer: Buffer,
    metadata: CaptureMetadata,
  ): Promise<{
    identity: MediaIdentity;
    registration: ApiResponse<RegistryRecord>;
  }> {
    const identity = this.createIdentity(mediaBuffer, metadata);
    const registration = await this.register(identity);
    return { identity, registration };
  }

  /**
   * Verify a media file by uploading it to the server.
   *
   * @param mediaBuffer - Raw bytes of the media to verify
   * @returns Verification result
   */
  async verifyByUpload(
    mediaBuffer: Buffer,
  ): Promise<ApiResponse<VerificationResult>> {
    const formData = new FormData();
    const blob = new Blob([mediaBuffer]);
    formData.append("media", blob, "verify-media");

    const response = await fetch(`${this.serverUrl}/api/v1/verify/upload`, {
      method: "POST",
      body: formData,
      signal: AbortSignal.timeout(this.timeout),
    });

    return response.json() as Promise<ApiResponse<VerificationResult>>;
  }

  /**
   * Verify a media file by content hash lookup.
   *
   * @param contentHash - SHA-256 hash of the media
   * @returns Lookup result with registry record
   */
  async verifyByHash(contentHash: string): Promise<
    ApiResponse<{
      record: RegistryRecord;
      signatureValid: boolean;
    }>
  > {
    const response = await fetch(
      `${this.serverUrl}/api/v1/verify/${contentHash}`,
      { signal: AbortSignal.timeout(this.timeout) },
    );

    return response.json() as Promise<
      ApiResponse<{ record: RegistryRecord; signatureValid: boolean }>
    >;
  }

  /**
   * Look up a media identity by its identity code.
   *
   * @param code - Identity code (MPROV-XXXX-XXXX-XXXX)
   * @returns Registry record
   */
  async lookupByCode(code: string): Promise<ApiResponse<RegistryRecord>> {
    const response = await fetch(
      `${this.serverUrl}/api/v1/lookup/code/${code}`,
      { signal: AbortSignal.timeout(this.timeout) },
    );

    return response.json() as Promise<ApiResponse<RegistryRecord>>;
  }

  /**
   * Look up a media identity by its UUID.
   *
   * @param mediaId - Media UUID
   * @returns Registry record
   */
  async lookupById(mediaId: string): Promise<ApiResponse<RegistryRecord>> {
    const response = await fetch(
      `${this.serverUrl}/api/v1/lookup/id/${mediaId}`,
      { signal: AbortSignal.timeout(this.timeout) },
    );

    return response.json() as Promise<ApiResponse<RegistryRecord>>;
  }

  /**
   * Perform local-only verification (no server needed).
   * Requires the original media and the registry record.
   *
   * @param mediaBuffer - Raw bytes of the media
   * @param record - The registry record to verify against
   * @returns Detailed verification result
   */
  verifyLocally(
    mediaBuffer: Buffer,
    record: RegistryRecord,
  ): VerificationResult {
    return verifyMedia(mediaBuffer, record);
  }

  /**
   * Compute content hash locally (for quick comparison).
   *
   * @param mediaBuffer - Raw bytes of the media
   * @returns SHA-256 hex hash
   */
  computeHash(mediaBuffer: Buffer): string {
    return hashContent(mediaBuffer);
  }
}
